name: Run Tests and Upload Report

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate report
      run: |
        pytest --html=pytest_report.html

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: pytest_report
        path: pytest_report.html
